### ISSUE TITLE
http-gateway crash

### ISSUE THREAD

**Issue by dyisdog** [vesoft-inc/nebula-http-gateway#116]
dashboard: nebula-dashboard-1.1.0.x86_64
nebula version: 
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/46206183/169180250-2b886159-720e-4954-b62a-b61e404bd990.png">

nodejs version : v10.24.0

golang version: go version go1.16.12 linux/amd64

1. nebula-http-gateway
<img width="404" alt="image" src="https://user-images.githubusercontent.com/46206183/169180443-191ccbe6-4058-4e9f-81e8-1d372cacc25a.png">
2. nebula-dashboard
<img width="525" alt="image" src="https://user-images.githubusercontent.com/46206183/169180507-7db6921c-a976-4325-b29e-dcd61cf1d358.png">

Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/runtime/panic.go:1038
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/runtime/panic.go:221
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/runtime/signal_unix.go:735
2022/05/18 16:28:26.850 [C] [config.go:194]  /__w/nebula-dashboard/nebula-dashboard/source/nebula-http-gateway/controllers/db.go:52
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/reflect/value.go:556
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/reflect/value.go:339
2022/05/18 16:28:26.850 [C] [config.go:194]  /github/home/go/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:897
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/net/http/server.go:2879
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/net/http/server.go:1930
2022/05/18 16:28:26.850 [C] [config.go:194]  /__t/go/1.17.6/x64/src/runtime/asm_amd64.s:1581
2022/05/18 16:28:26.850 [log.go:191]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)

**Comment by kqzh** [comment]
hi @dyisdog , can you tell you tell me what you did before gateway crash ?

**Comment by dyisdog** [comment]
> hi @dyisdog , can you tell you tell me what you did before gateway crash ?

dashboard ,username don`t use root

**Comment by kqzh** [comment]
> 

so, if username is root, gateway will not crash? we will try to reproduce it, thanks for your information

**Comment by kqzh** [comment]
fixed
