### ISSUE TITLE
这个直接http请求的话，是否能再Windows上面直接测试，需要安装什么？安装方式在哪里查看？

### ISSUE THREAD

**Issue by LHH-James** [vesoft-inc/nebula-http-gateway#22]

**Comment by wey-gu** [comment]
You can run this via Linux VMs backed with WSL(or Virtualbox) or inside a Linux container via Docker Desktop.

To be built and run natively in Windows, it may be possible if you manage to install the windows-port of CMake together with golang, which it's not yet verified by our side.

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
