### ISSUE TITLE
configBody JSON schema

### ISSUE THREAD

**Issue by sunkararp** [vesoft-inc/nebula-http-gateway#71]
Can someone please document configBody JSON body schema or provide sample JSON files?

We wanted to call /api-nebula/task/import to bulk ingest Vertices and Edges.

**Comment by hetao92** [comment]
{
        "version": "v2", 
        "description": "web console import", 
        "removeTempFiles": null, 
        "clientSettings": {
            "retry": 3, 
            "concurrency": 10, 
            "channelBufferSize": 128, 
            "space": "nba", 
            "connection": {
                "user": "root", 
                "password": "nebula", 
                "address": "127.0.0.1:9669"
            }
        }, 
        "logPath": "import.log", 
        "files": [
            {
                "path": "player.csv", 
                "failDataPath": "playerFail.csv", 
                "batchSize": 60, 
                "limit": null, 
                "inOrder": null, 
                "type": "csv", 
                "csv": {
                    "withHeader": false, 
                    "withLabel": false, 
                    "delimiter": null
                }, 
                "schema": {
                    "type": "vertex", 
                    "edge": null, 
                    "vertex": {
                        "vid": {
                            "index": 0, 
                            "function": null, 
                            "type": "string", 
                            "prefix": null
                        }, 
                        "tags": [
                            {
                                "name": "player", 
                                "props": [
                                    {
                                        "name": "name", 
                                        "type": "string", 
                                        "index": 1
                                    }, 
                                    {
                                        "name": "age", 
                                        "type": "int", 
                                        "index": 2
                                    }
                                ]
                            }
                        ]
                    }
                }
            }, 
            {
                "path": "team.csv", 
                "failDataPath": "teamFail.csv", 
                "batchSize": 60, 
                "limit": null, 
                "inOrder": null, 
                "type": "csv", 
                "csv": {
                    "withHeader": false, 
                    "withLabel": false, 
                    "delimiter": null
                }, 
                "schema": {
                    "type": "vertex", 
                    "edge": null, 
                    "vertex": {
                        "vid": {
                            "index": 0, 
                            "function": null, 
                            "type": "string", 
                            "prefix": null
                        }, 
                        "tags": [
                            {
                                "name": "team", 
                                "props": [
                                    {
                                        "name": "name", 
                                        "type": "string", 
                                        "index": 1
                                    }
                                ]
                            }
                        ]
                    }
                }
            }, 
            {
                "path": "like.csv", 
                "failDataPath": "likeFail.csv", 
                "batchSize": 60, 
                "limit": null, 
                "inOrder": null, 
                "type": "csv", 
                "csv": {
                    "withHeader": false, 
                    "withLabel": false, 
                    "delimiter": null
                }, 
                "schema": {
                    "type": "edge", 
                    "edge": {
                        "name": "like", 
                        "withRanking": false, 
                        "props": [
                            {
                                "name": "likeness", 
                                "type": "int", 
                                "index": 2
                            }
                        ], 
                        "srcVID": {
                            "index": 0, 
                            "function": null, 
                            "type": "string", 
                            "prefix": null
                        }, 
                        "dstVID": {
                            "index": 1, 
                            "function": null, 
                            "type": "string", 
                            "prefix": null
                        }, 
                        "rank": null
                    }, 
                    "vertex": null
                }
            }, 
            {
                "path": "serve.csv", 
                "failDataPath": "serveFail.csv", 
                "batchSize": 60, 
                "limit": null, 
                "inOrder": null, 
                "type": "csv", 
                "csv": {
                    "withHeader": false, 
                    "withLabel": false, 
                    "delimiter": null
                }, 
                "schema": {
                    "type": "edge", 
                    "edge": {
                        "name": "serve", 
                        "withRanking": false, 
                        "props": [
                            {
                                "name": "start_year", 
                                "type": "int", 
                                "index": 3
                            }, 
                            {
                                "name": "end_year", 
                                "type": "int", 
                                "index": 4
                            }
                        ], 
                        "srcVID": {
                            "index": 0, 
                            "function": null, 
                            "type": "string", 
                            "prefix": null
                        }, 
                        "dstVID": {
                            "index": 1, 
                            "function": null, 
                            "type": "string", 
                            "prefix": null
                        }, 
                        "rank": null
                    }, 
                    "vertex": null
                }
            }
        ]
    },

**Comment by hetao92** [comment]
Btw, you can use nebula-studio to import data.  It uses the same implementation method as gateway, using nebula importer to import data

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime. Thanks a lot for your contribution.
