### ISSUE TITLE
is it support the api list docs? like swagger（for Java：https://github.com/nebula-contrib/graph-gateway）

### ISSUE THREAD

**Issue by mathlpz** [vesoft-inc/nebula-http-gateway#86]
can it support the api list docs? easy for developer debug. like swagger...

**Comment by hetao92** [comment]
Thank you for your suggestion, we will improve the document in the future

**Comment by mathlpz** [comment]
the java coder can refer to [graph-gateway](https://github.com/nebula-contrib/graph-gateway) for server development similarly.
